// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP0id5LUU_pOQg261ehaKIF3nwChMC2YM',
    appId: '1:98829966016:web:fb06d59e16191feca9eb25',
    messagingSenderId: '98829966016',
    projectId: 'growappp-3b2dd',
    authDomain: 'growappp-3b2dd.firebaseapp.com',
    storageBucket: 'growappp-3b2dd.firebasestorage.app',
    measurementId: 'G-J48VFEYHQD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOXOFiUnHWFZSKrATVyu7mO22p5-3KZ1w',
    appId: '1:98829966016:ios:ebe0db09c8efe602a9eb25',
    messagingSenderId: '98829966016',
    projectId: 'growappp-3b2dd',
    storageBucket: 'growappp-3b2dd.firebasestorage.app',
    iosBundleId: 'com.growapp.growapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP0id5LUU_pOQg261ehaKIF3nwChMC2YM',
    appId: '1:98829966016:web:060c4dccae11ef0fa9eb25',
    messagingSenderId: '98829966016',
    projectId: 'growappp-3b2dd',
    authDomain: 'growappp-3b2dd.firebaseapp.com',
    storageBucket: 'growappp-3b2dd.firebasestorage.app',
    measurementId: 'G-H0M1DZYKNC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOXOFiUnHWFZSKrATVyu7mO22p5-3KZ1w',
    appId: '1:98829966016:ios:ebe0db09c8efe602a9eb25',
    messagingSenderId: '98829966016',
    projectId: 'growappp-3b2dd',
    storageBucket: 'growappp-3b2dd.firebasestorage.app',
    iosBundleId: 'com.growapp.growapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr9zZ-e3ClqhVaKbi_D6bT-pOueIdXCzE',
    appId: '1:98829966016:android:8350816f074a6dd0a9eb25',
    messagingSenderId: '98829966016',
    projectId: 'growappp-3b2dd',
    storageBucket: 'growappp-3b2dd.firebasestorage.app',
  );

}